/***********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2015 by Vector Informatik GmbH.                                               All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 * --------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 * ------------------------------------------------------------------------------------------------------------------*/
/**     \file  TscDem.h
 *     \brief  TscStub header file for Dem
 *   \details  
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  AUTHOR IDENTITY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Name                          Initials      Company
 *  -------------------------------------------------------------------------------------------------------------------
 *                              vismas           Vector Informatik GmbH
 *  -------------------------------------------------------------------------------------------------------------------
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Version   Date        Author  ChangeId      Description
 *  -------------------------------------------------------------------------------------------------------------------
 *  1.0       2014-11-19  vismas  ESCAN0000000  generated by EA
 **********************************************************************************************************************/

#if !defined(TSCDEM_HEADER)
#define TSCDEM_HEADER

/***********************************************************************************************************************
 *  INCLUDES
 **********************************************************************************************************************/
#include "Dem.h"

/***********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 **********************************************************************************************************************/
/*--- Version Data --------------------------------------------------------------------------------------------------*/
#define TSCDEM_MAJOR_VERSION                                                  (1U)
#define TSCDEM_MINOR_VERSION                                                  (0U)
#define TSCDEM_RELEASE_VERSION                                                (0U)

/*--- standard BTE data defines -------------------------------------------------------------------------------------*/
#define kTscDem_CI                                                                    0x01

/*--- wrapper function symbols --------------------------------------------------------------------------------------*/

/*--- stub function symbols -----------------------------------------------------------------------------------------*/
#define kTscDem_Dem_ReportErrorStatus                                                 0x01


/***********************************************************************************************************************
 *  GLOBAL FUNCTION MACROS
 **********************************************************************************************************************/
/*--- standard BTE macros -------------------------------------------------------------------------------------------*/
#define TscDem_EventMask_EnableAll()            BteLog_EventMask_EnableAll( kTscDem_CI )
#define TscDem_EventMask_DisableAll()           BteLog_EventMask_DisableAll( kTscDem_CI )
#define TscDem_EventMask_Enable(eventId)        BteLog_EventMask_Enable( kTscDem_CI, eventId )
#define TscDem_EventMask_Disable(eventId)       BteLog_EventMask_Disable( kTscDem_CI, eventId )
#define TscDem_EventListMask_EnableAll()        BteLog_EventListMask_EnableAll( kTscDem_CI )
#define TscDem_EventListMask_DisableAll()       BteLog_EventListMask_DisableAll( kTscDem_CI )
#define TscDem_EventListMask_Enable(eventId)    BteLog_EventListMask_Enable( kTscDem_CI, eventId )
#define TscDem_EventListMask_Disable(eventId)   BteLog_EventListMask_Disable( kTscDem_CI, eventId )
#define TscDem_EventLogMask_EnableAll()         BteLog_EventLogMask_EnableAll( kTscDem_CI )
#define TscDem_EventLogMask_DisableAll()        BteLog_EventLogMask_DisableAll( kTscDem_CI )
#define TscDem_EventLogMask_Enable(eventId)     BteLog_EventLogMask_Enable( kTscDem_CI, eventId )
#define TscDem_EventLogMask_Disable(eventId)    BteLog_EventLogMask_Disable( kTscDem_CI, eventId )



/***********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  GLOBAL FUNCTION PROTOTYPES
 **********************************************************************************************************************/
/*--- standard BTE function prototypes ------------------------------------------------------------------------------*/
void TscDem_Init( void );
void TscDem_Cyclic1ms( void );

/*--- wrapper function prototypes -----------------------------------------------------------------------------------*/

/*--- stub function prototypes --------------------------------------------------------------------------------------*/
/* prototype for Dem_ReportErrorStatus defined in Dem.h */

/*--- stub function control prototypes ------------------------------------------------------------------------------*/

/*--- stub assert event function prototypes -------------------------------------------------------------------------*/


#endif /* TSCDEM_HEADER */
/***********************************************************************************************************************
 *  END OF FILE
 **********************************************************************************************************************/

